### ISSUE TITLE
Fetch jokes by category

### ISSUE THREAD

**Issue by swapnil-musale** [swapnil-musale/JetJoke#56]
Current Behaviour : 
App fetch the jokes using ```https://v2.jokeapi.dev/joke/Any``` this api. Where as joke api provider allow fetch category specific joke using same api.

To fetch the available joke categories we need to call ```https://v2.jokeapi.dev/categories``` this api.
Response : 
```
{
    "error": false,
    "categories": [
        "Any",
        "Misc",
        "Programming",
        "Dark",
        "Pun",
        "Spooky",
        "Christmas"
    ],
    "categoryAliases": [
        {
            "alias": "Miscellaneous",
            "resolved": "Misc"
        },
        {
            "alias": "Coding",
            "resolved": "Programming"
        },
        {
            "alias": "Development",
            "resolved": "Programming"
        },
        {
            "alias": "Halloween",
            "resolved": "Spooky"
        }
    ],
    "timestamp": 1692770989674
}
```

In above response we will receive ```categories``` string array list and same will be used to display categories in home screen.
By default 1st category will be auto selected and upon other category selection we will call this ```https://v2.jokeapi.dev/joke/{category-name}``` api to fetch joke.

Currently I'm thinking to add category list above the Joke Card in home screen in horizontal fashion. (For more clearity checkout Youtube App -> Top Section  horizontal rail is displayed).

But this is just my idea if you have any better design I'm open to incorporate with it.

**Comment by iam-subho** [comment]
@swapnil-musale can i contribute to add this features into the app???
